import { MODELS } from "../../core/ports/ILanguageModel.js";
import type { ILanguageModel } from "../../core/ports/ILanguageModel.js";
import type { ResearchDraftPatch, ResearchSource } from "../../shared/types.js";

// ─── Types ─────────────────────────────────────────────────────────────────────

export type SectionKey =
  | "business"
  | "moat"
  | "management"
  | "financials"
  | "scenarios"
  | "catalyst";

export interface SectionResult {
  key:       SectionKey;
  content:   string;          // markdown prose generated by IA
  question:  string;          // the Socratic question to ask the user
  patch:     ResearchDraftPatch;
  sources:   ResearchSource[];
}

export interface SectionInput {
  ticker:      string;
  sectionKey:  SectionKey;
  facts:       string;         // EDGAR financial facts
  userNote?:   string;         // optional user correction/addition
  priorDraft:  ResearchDraftPatch;
}

// ─── Section config ────────────────────────────────────────────────────────────

export const SECTIONS: { key: SectionKey; label: string; icon: string }[] = [
  { key: "business",   label: "Business",      icon: "01" },
  { key: "moat",       label: "Moat",          icon: "02" },
  { key: "management", label: "Management",    icon: "03" },
  { key: "financials", label: "Financials",    icon: "04" },
  { key: "scenarios",  label: "Scenarios",     icon: "05" },
  { key: "catalyst",   label: "Catalyst",      icon: "06" },
];

// ─── EDGAR data fetch ──────────────────────────────────────────────────────────

export async function fetchEdgarFacts(ticker: string): Promise<string> {
  try {
    const tickerRes = await fetch("https://www.sec.gov/files/company_tickers.json", {
      headers: { "User-Agent": "EfrainAI-ResearchBot/1.0" },
      signal:  AbortSignal.timeout(5000),
    });
    if (!tickerRes.ok) return "";

    const tickerMap = await tickerRes.json() as Record<string, { cik_str: number; ticker: string; title: string }>;
    const entry = Object.values(tickerMap).find(
      e => e.ticker.toLowerCase() === ticker.toLowerCase(),
    );
    if (!entry) return "";

    const cik      = String(entry.cik_str).padStart(10, "0");
    const factsRes = await fetch(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`, {
      headers: { "User-Agent": "EfrainAI-ResearchBot/1.0" },
      signal:  AbortSignal.timeout(8000),
    });
    if (!factsRes.ok) return "";

    const facts = await factsRes.json() as {
      entityName?: string;
      facts?: {
        "us-gaap"?: Record<string, { units?: { USD?: { end?: string; val?: number; form?: string }[] } }>;
      };
    };

    const gaap  = facts.facts?.["us-gaap"] ?? {};
    const lines: string[] = [`Company: ${facts.entityName ?? ticker}`];

    const metrics: Record<string, string> = {
      Revenues: "Revenue",
      RevenueFromContractWithCustomerExcludingAssessedTax: "Revenue",
      NetIncomeLoss:       "Net Income",
      GrossProfit:         "Gross Profit",
      OperatingIncomeLoss: "Operating Income",
      Assets:              "Total Assets",
      CashAndCashEquivalentsAtCarryingValue: "Cash",
      StockholdersEquity:  "Equity",
      ResearchAndDevelopmentExpense: "R&D Expense",
      CommonStockSharesOutstanding:  "Shares Outstanding",
    };

    for (const [key, label] of Object.entries(metrics)) {
      const series = gaap[key]?.units?.USD;
      if (!series) continue;
      const annual = series
        .filter(v => v.form === "10-K" && v.end && v.val !== undefined)
        .sort((a, b) => (b.end ?? "").localeCompare(a.end ?? ""));
      if (annual[0]) {
        const val       = annual[0].val!;
        const formatted = val >= 1e9
          ? `$${(val / 1e9).toFixed(1)}B`
          : val >= 1e6
          ? `$${(val / 1e6).toFixed(0)}M`
          : `$${val.toLocaleString()}`;
        lines.push(`${label} (${annual[0].end?.slice(0, 4) ?? ""}): ${formatted}`);
      }
    }

    return lines.join("\n");
  } catch {
    return "";
  }
}

export async function fetchEdgarFilings(ticker: string): Promise<ResearchSource[]> {
  const sources: ResearchSource[] = [];
  try {
    const res = await fetch(
      `https://efts.sec.gov/LATEST/search-index?q=%22${encodeURIComponent(ticker)}%22&dateRange=custom&startdt=2024-01-01&forms=10-K,10-Q,8-K`,
      { headers: { "User-Agent": "EfrainAI-ResearchBot/1.0" }, signal: AbortSignal.timeout(6000) },
    );
    if (res.ok) {
      const data = await res.json() as {
        hits?: { hits?: { _source?: { form_type?: string; file_date?: string; entity_name?: string } }[] };
      };
      for (const hit of (data?.hits?.hits ?? []).slice(0, 3)) {
        const src = hit._source;
        if (src) {
          sources.push({
            title:   `${src.entity_name ?? ticker} — ${src.form_type ?? "Filing"} (${src.file_date ?? ""})`,
            url:     `https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&company=${encodeURIComponent(ticker)}&type=10-K&dateb=&owner=include&count=5`,
            type:    "sec_filing",
            snippet: `${src.form_type} filed ${src.file_date ?? ""}`,
          });
        }
      }
    }
  } catch { /* silently skip */ }

  if (sources.length === 0) {
    sources.push({
      title:   `${ticker} — SEC EDGAR`,
      url:     `https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&company=${encodeURIComponent(ticker)}&type=10-K&dateb=&owner=include&count=5`,
      type:    "sec_filing",
      snippet: `Latest filings for ${ticker}`,
    });
  }
  return sources;
}

// ─── Section prompts ───────────────────────────────────────────────────────────

const SECTION_PROMPTS: Record<SectionKey, (ticker: string, facts: string, userNote: string, draft: ResearchDraftPatch) => string> = {

  business: (ticker, facts, userNote, _draft) => `
You are an equity research analyst. Analyze ${ticker} and write the BUSINESS section of an investment thesis.

EDGAR DATA:
${facts || "Not available — use your knowledge."}

${userNote ? `ANALYST NOTE: ${userNote}` : ""}

Write 3-4 concise paragraphs covering:
1. What the company does and how it makes money (core revenue streams)
2. The market it serves — size, growth rate, competitive dynamics
3. Key operational metrics and recent performance trends
4. Geographic exposure and concentration risks

Be specific, cite numbers where available. No filler sentences.

After your analysis, output a JSON block in <patch> tags:
<patch>
{
  "business_summary": "...",
  "economic_domain": "biological|physical|digital|mixed",
  "geographic_exposure": "...",
  "key_metrics": "..."
}
</patch>

Then write ONE sharp question for the analyst — something that would materially change the thesis if answered differently. Start it with "→"
`,

  moat: (ticker, facts, userNote, draft) => `
You are an equity research analyst. Analyze ${ticker}'s competitive moat.

EDGAR DATA:
${facts || "Not available — use your knowledge."}

BUSINESS CONTEXT: ${draft.business_summary ?? "Not yet analyzed."}

${userNote ? `ANALYST NOTE: ${userNote}` : ""}

Write 2-3 paragraphs covering:
1. The primary source of competitive advantage (brand, costs, network effects, switching costs, regulatory)
2. Concrete evidence: gross margins vs peers, retention rates, pricing power, customer lock-in
3. Durability assessment — what could erode this moat over 3-5 years

Be direct. If there is no clear moat, say so.

After your analysis, output a JSON block in <patch> tags:
<patch>
{
  "moat_type": "brand|costs|network|regulatory|other|none",
  "moat_evidence": "..."
}
</patch>

Then write ONE sharp question for the analyst. Start it with "→"
`,

  management: (ticker, facts, userNote, draft) => `
You are an equity research analyst. Analyze ${ticker}'s management quality.

EDGAR DATA:
${facts || "Not available — use your knowledge."}

BUSINESS CONTEXT: ${draft.business_summary ?? "Not yet analyzed."}

${userNote ? `ANALYST NOTE: ${userNote}` : ""}

Write 2-3 paragraphs covering:
1. Founder vs professional management, tenure, ownership stake
2. Capital allocation track record: M&A, buybacks, dividends, reinvestment
3. Key decisions (good and bad) in the last 3 years and what they reveal

Be critical where warranted. Insider ownership data and compensation structure are important signals.

After your analysis, output a JSON block in <patch> tags:
<patch>
{
  "management_notes": "..."
}
</patch>

Then write ONE sharp question for the analyst. Start it with "→"
`,

  financials: (ticker, facts, userNote, draft) => `
You are an equity research analyst. Analyze ${ticker}'s financial profile.

EDGAR DATA:
${facts || "Not available — use your knowledge."}

BUSINESS CONTEXT: ${draft.business_summary ?? "Not yet analyzed."}
MOAT: ${draft.moat_type ?? "Unknown"} — ${draft.moat_evidence ?? ""}

${userNote ? `ANALYST NOTE: ${userNote}` : ""}

Write 2-3 paragraphs covering:
1. Revenue growth trend (3-year CAGR), gross margin stability, operating leverage
2. FCF generation, capital intensity, return on invested capital (ROIC)
3. Balance sheet: net cash/debt position, leverage ratio, covenant risks

Include specific numbers. Flag any deteriorating trends or accounting concerns.

After your analysis, output a JSON block in <patch> tags:
<patch>
{
  "key_metrics": "Rev growth · Gross margin · ROIC · Net cash/debt · EV/EBITDA · P/FCF"
}
</patch>

Then write ONE sharp question for the analyst. Start it with "→"
`,

  scenarios: (ticker, facts, userNote, draft) => `
You are an equity research analyst. Build Bull / Base / Bear scenarios for ${ticker}.

EDGAR DATA:
${facts || "Not available — use your knowledge."}

CONTEXT:
- Business: ${draft.business_summary ?? "Not yet analyzed."}
- Moat: ${draft.moat_type ?? "Unknown"}
- Financials: ${draft.key_metrics ?? "Not yet analyzed."}

${userNote ? `ANALYST NOTE: ${userNote}` : ""}

For each scenario write:
- The core assumption that drives it
- Implied revenue/EPS for the target year
- Price target with derivation (e.g. "EPS $3.20 × 45x = $144")
- Probability (Bull + Base + Bear must sum to 100%)

Use realistic, differentiated probabilities (not 33/33/33).

After your analysis, output a JSON block in <patch> tags:
<patch>
{
  "bull_triggers": "...",
  "bull_pt": "$X · EPS $Y × Zx",
  "base_narrative": "...",
  "base_pt": "$X · EPS $Y × Zx",
  "bear_risk": "...",
  "invalidation": "..."
}
</patch>

Then write ONE sharp question for the analyst. Start it with "→"
`,

  catalyst: (ticker, facts, userNote, draft) => `
You are an equity research analyst. Identify the investment catalyst for ${ticker}.

EDGAR DATA:
${facts || "Not available — use your knowledge."}

CONTEXT:
- Business: ${draft.business_summary ?? "Not yet analyzed."}
- Scenarios: Bull ${draft.bull_pt ?? "?"} / Base ${draft.base_pt ?? "?"} / Bear ${draft.bear_risk ?? "?"}

${userNote ? `ANALYST NOTE: ${userNote}` : ""}

Write 2 paragraphs:
1. The specific event or dynamic that makes this timely — why should the market re-rate within 12 months? (earnings beat, product launch, regulatory approval, management change, sector rotation, macro shift)
2. The main thesis in one crisp sentence: "We believe ${ticker} is [undervalued/overlooked/misunderstood] because [X], and the market will recognize this when [catalyst]."

Be specific. Vague catalysts destroy investment theses.

After your analysis, output a JSON block in <patch> tags:
<patch>
{
  "catalyst": "...",
  "main_thesis": "..."
}
</patch>

Then write ONE sharp question for the analyst — the single most important question that could invalidate this entire thesis. Start it with "→"
`,
};

// ─── Run section ───────────────────────────────────────────────────────────────

export async function* runSection(
  llm: ILanguageModel,
  input: SectionInput,
): AsyncGenerator<string, SectionResult> {
  const { ticker, sectionKey, facts, userNote, priorDraft } = input;

  const prompt = SECTION_PROMPTS[sectionKey](ticker, facts, userNote ?? "", priorDraft);

  let fullText = "";
  const stream = llm.chatStream({
    model:       MODELS.sonnet,
    system:      `You are a rigorous equity research analyst. Be concise, specific, and evidence-based. Never use filler phrases like "it's worth noting" or "it is important to consider".`,
    user:        prompt,
    temperature: 0.3,
    max_tokens:  1200,
  });

  for await (const token of stream) {
    fullText += token;
    yield token;
  }

  // Extract patch
  const patch    = extractPatch(fullText, priorDraft);
  // Extract question (line starting with →)
  const question = extractQuestion(fullText);
  // Clean content (remove patch block)
  const content  = fullText.replace(/<patch>[\s\S]*?<\/patch>/g, "").trim();

  return { key: sectionKey, content, question, patch, sources: [] };
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function extractPatch(text: string, existing: ResearchDraftPatch): ResearchDraftPatch {
  const match = text.match(/<patch>([\s\S]*?)<\/patch>/);
  if (!match) return existing;
  try {
    const raw   = JSON.parse(match[1].trim()) as Record<string, string>;
    const patch = { ...existing };
    for (const [k, v] of Object.entries(raw)) {
      if (typeof v === "string" && v.trim()) {
        (patch as Record<string, unknown>)[k] = v.trim();
      }
    }
    return patch;
  } catch {
    return existing;
  }
}

function extractQuestion(text: string): string {
  const lines = text.split("\n");
  for (const line of lines.reverse()) {
    const trimmed = line.trim();
    if (trimmed.startsWith("→")) return trimmed.slice(1).trim();
  }
  return "";
}
